# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=32, verbose_name='Организация')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Регион')),
                ('site', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('position', models.CharField(max_length=16, verbose_name='Должность')),
                ('duties', models.TextField(verbose_name='Обязанности')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='Время работы')),
            ],
        ),
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_q', models.CharField(max_length=32, verbose_name='Название')),
                ('description_q', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=32, verbose_name='Группа')),
                ('categorized', models.CharField(max_length=32, verbose_name='Категория')),
            ],
        ),
    ]
